export { default as NewDelivery } from './NewDelivery.vue'
export { default as DeliveryTableRow } from './DeliveryTableRow.vue'
export { default as DeliveryTable } from './DeliveryTable.vue'
export { default as EditDelivery } from './EditDelivery.vue'
export { default as LoginForm } from './LoginForm.vue'
export { default as AppFooter } from './AppFooter.vue'
